name: Apptainer Build Deploy

on:
  pull_request:
  push:
    branches: master

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    container:
        image: quay.io/singularity/singularity:v3.8.1
        options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v2

      - name: Build Container
        run: |
           singularity build ${{ github.event.repository.name }}.sif test.def

      - name: Login and Deploy Container
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
           singularity push ${{ github.event.repository.name }}.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}

    #   - name: 'Upload Artifact'
    #     uses: actions/upload-artifact@v4
    #     with:
    #         name: test-artifact
    #         path: test-container.sif
    #         retention-days: 5

      - name: Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "${{ github.event.repository.name }}.sif"
            bodyFile: "README.md"